using System;
using System.Runtime.Serialization;

namespace  Digipolis.Persoon.Api.Models.PersoonOpvraging
{
    public enum Eigenschap
    {
        //Optie alles niet meer toegelaten.
        //Het is vrijwel onmogelijk dat alles nodig is.
        //Dit zorgt voor onnodige vertragingen en load op persoon.
        //Alles,
        //AllesMetHistoriek,
        AangifteBuitenlandsAdres,
        AanvraagInschrijving,
        ActiefAdres,
        Adeltitel,
        AdresWijziging,
        Afstamming,
        Afwezigheid,
        ArbeidsKaart,
        Audit,
        Beroep,
        BeroepsKaart,
        Bron,
        BuitenlandsAdres,
        BuitenlandsPostAdres,
        BurgerlijkeStaat,
        Certificaat,
        ContactGegevens,
        Geboorte,
        GemeenteVanVerblijf,
        GevalideerdBuitenlandsAdres,
        HuidigeToestand,
        IdentiteitsBewijs,
        Naam,
        Nationaliteit,
        OfficieelAdres,
        Overlijden,
        Paspoort,
        ReferentieAdresDatum,
        Register,
        Rekeningen,
        TijdelijkeAfwezigheid,
        VerblijfsAdres,
        Vertegenwoordiger,
        Vertegenwoordiging,
        VerzendAdres,
        VorigeCrsNummers,
        Vreemdeling,
        WettelijkeSamenwoning,
        WettelijkeWoonplaats,
        AangifteBuitenlandsAdresMetHistoriek,
        AanvraagInschrijvingMetHistoriek,
        AdeltitelMetHistoriek,
        AdresWijzigingMetHistoriek,
        AfstammingMetHistoriek,
        AfwezigheidMetHistoriek,
        ArbeidsKaartMetHistoriek,
        BeroepMetHistoriek,
        BeroepsKaartMetHistoriek,
        BuitenlandsAdresMetHistoriek,
        BuitenlandsPostAdresMetHistoriek,
        BurgerlijkeStaatMetHistoriek,
        CertificaatMetHistoriek,
        ContactGegevensMetHistoriek,
        GeboorteMetHistoriek,
        GemeenteVanVerblijfMetHistoriek,
        GevalideerdBuitenlandsAdresMetHistoriek,
        IdentiteitsBewijsMetHistoriek,
        NaamMetHistoriek,
        NationaliteitMetHistoriek,
        OfficieelAdresMetHistoriek,
        OverlijdenMetHistoriek,
        PaspoortMetHistoriek,
        ReferentieAdresDatumMetHistoriek,
        RegisterMetHistoriek,
        RekeningenMetHistoriek,
        TijdelijkeAfwezigheidMetHistoriek,
        VerblijfsAdresMetHistoriek,
        VertegenwoordigerMetHistoriek,
        VertegenwoordigingMetHistoriek,
        VerzendAdresMetHistoriek,
        VreemdelingMetHistoriek,
        WettelijkeSamenwoningMetHistoriek,
        WettelijkeWoonplaatsMetHistoriek
    }
    //Gezinshistoriek wordt niet ondersteunt.
    //GezinsLedenMetHistoriek,
}